### ISSUE TITLE
Webhooks Rails 5

### ISSUE THREAD

**Issue by matthewford** [contentful/contentful_rails#36] opened 2017-05-18 12:16 UTC
Hi,

I get errors with the webhooks engine in Rails 5 (on master)

```
Processing by ContentfulRails::WebhooksController#create as JSON
NoMethodError (undefined method `[]' for nil:NilClass): 
 vendor/bundle/ruby/2.3.0/bundler/gems/contentful_rails-d1d3c62141da/lib/contentful_rails/engine.rb:39:in `block (2 levels) in <class:Engine>' 
```

**Comment by damienh** [comment] 2017-09-27 13:11
I also get this when the webhook is `"X-Contentful-Topic": "ContentManagement.Entry.publish",`

However `"X-Contentful-Topic": "ContentManagement.Entry.auto_save"` calls return `200`.  

Using Rails 5.

**Comment by dlitvakb** [comment] 2017-09-27 13:28
Hey @matthewford and @damienh,

Thanks for submitting the bug.

I'll take a look into this as soon as I can.

Cheers

**Comment by damienh** [comment] 2017-09-29 09:18
@dlitvakb Did some digging around and have a PR that solves this https://github.com/contentful/contentful_rails/pull/37

**Comment by dlitvakb** [comment] 2017-09-29 10:27
Hey @damienh, I tried your PR and looks like it's working, it has been merged! Thanks.

@matthewford can you confirm if you still have the issue when updating to master branch?

Cheers

**Comment by jonhainstock** [comment] 2018-01-16 02:54
I just wanted to let you know that this PR worked for me. I'm running Rails 5.1.4. Thanks @damienh!

**Comment by dlitvakb** [comment] 2018-02-06 14:56
Closing, as this is confirmed to work.

Cheers

**Closed by dlitvakb** 2018-02-06 14:56 UTC
